package org.kie.example.project1;

import org.drools.core.util.KieFunctions;
/**
 * This class was automatically generated by the data modeler tool.
 */

public class adhoc implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String status;

   public adhoc()
   {
   }

   public java.lang.String getStatus()
   {
      return this.status;
   }

   public void setStatus(java.lang.String status)
   {
      this.status = status;
   }

   public adhoc(java.lang.String status)
   {
      this.status = status;
   }

}