package org.kie.example.project1;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Xyz implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label(value = "name")
   private java.lang.String name;

   public Xyz()
   {
   }

   public java.lang.String getName()
   {
      return this.name;
   }

   public void setName(java.lang.String name)
   {
      this.name = name;
   }

   public Xyz(java.lang.String name)
   {
      this.name = name;
   }

}