package org.kie.example.project1;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class xyz implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label("Name")
   private java.lang.String name;

   @org.kie.api.definition.type.Label(value = "id")
   private java.lang.Integer id;

   public xyz()
   {
   }

   public java.lang.String getName()
   {
      return this.name;
   }

   public void setName(java.lang.String name)
   {
      this.name = name;
   }

   public java.lang.Integer getId()
   {
      return this.id;
   }

   public void setId(java.lang.Integer id)
   {
      this.id = id;
   }

   public xyz(java.lang.String name, java.lang.Integer id)
   {
      this.name = name;
      this.id = id;
   }

}